name: Auto Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Yarn Install
      run: yarn install

    - name: Yarn Test
      run: npx hardhat test

    - name: Deploy
      run: |
        mv .env.example .env
        yarn deploy:common-util
        yarn deploy:simple-erc20
        yarn deploy:simple-erc721
        yarn deploy:merkle-tree-verify